config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = ["White", "Green", "Red", "Orange", "Brown", "Yellow", "Blue"].freeze
  validates :sex, inclusion: ["M", "F"]
  validates :color, inclusion: COLORS
  validates :birth_date, :color, :name, :sex, :description, presence: true

  # has_many :rental_requests, dependent: :destroy

  def age
    today = Date.today
    ((today - self[:birth_date]) / 365).to_i
  end

end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: ['PENDING', 'APPROVED', 'DENIED']
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    CatRentalRequest
      .select('*')
      .where('(? BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date) OR
              (? BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date) OR
              (cat_rental_requests.start_date >= ? AND cat_rental_requests.end_date <= ?)',
              self.start_date, self.end_date, self.start_date, self.end_date)
      .where.not(id: self.id)
  end

  def overlapping_approved_requests
    self.overlapping_requests.select { |request| request.status == 'APPROVED' }
  end

  def does_not_overlap_approved_request
    byebug
    self.overlapping_approved_requests.none? { |request| CatRentalRequest.exists?(request) }
  end
end


# c2 = CatRentalRequest.new(cat_id: 2, start_date: Date.new(2017,8,8), end_date: Date.new(2017,8,15))

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save!
      redirect_to cats_url
    else
      render :new, status: 422
    end
  end

  def edit
    render :edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end

  def set_cat
    @cat = Cat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/views/cats/_cat.html.erb
<li>
<%= cat.name %>
<%= link_to "profile", cat_url(cat) %>
<%= button_to 'delete', cat_url(cat), method: :delete %>
</li>

app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(cat) %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name:</label>
  <input type="name" name="cat[name]" value=" <%= cat.name %>" >
  <br><br>

  <label for="sex">Sex:</label><br>
    Male<input type="radio" name="cat[sex]" value="M" checked=<%= cat.sex == "M" ? "true" : "false" %> >
    Female<input type="radio" name="cat[sex]" value="F" checked=<%= cat.sex == "F" ? "true" : "false"%>>

  <br><br>

  <label for="birth_date">Birth Date:</label>
  <input type="date" name="cat[birth_date]" value='<%= cat.birth_date %>'>
  <br><br>

  <label for="color">Color</label>
  <select name="cat[color]" >
    <%["White", "Green", "Red", "Orange", "Brown", "Yellow", "Blue"].each do |color| %>
      <% if color == cat.color %>
        <option value= <%= color %> selected="true" ><%= color %></option>
      <% else %>
        <option value= <%= color %> ><%= color %></option>
      <% end %>
    <% end %>
  </select>
  <br><br>


  <label for="description">Description:</label><br>
  <textarea name="cat[description]" rows='10' cols='50'> <%= cat.description %> </textarea>

  <br>
  <input type="submit" value='<%= action_url == :edit ? "Update!" : "Create!" %>'>
</form>

app/views/cats/edit.html.erb
<h1> Edit Cat! </h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>All the Cats!</h1>

<ul><%= render @cats %></ul>

<%= link_to 'Add a Cat', new_cat_url %>

app/views/cats/new.html.erb
<h1> Create a new Cat! </h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1><%= @cat.name  %></h1>
<table>
  <tr>
    <td>Birthday:</td>
    <td><%= @cat.birth_date %></td>
  </tr>

  <tr>
    <td>Age:</td>
    <td><%= @cat.age %></td>
  </tr>

  <tr>
    <td>Sex:</td>
    <td><%= @cat.sex %></td>
  </tr>

  <tr>
    <td>Color:</td>
    <td><%= @cat.color %></td>
  </tr>
</table>
<br>
<label for="cat-description">Description:</label>
<p><%= @cat.description %></p>

<h3><%= link_to 'edit', edit_cat_url(@cat) %></h3>
<h3><%= link_to 'Back to index', cats_url %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>